name: Verify code, provide apk
run-name: Verify code, provide apk for ${{ github.event.pull_request.title }}

on:
  schedule:
    - cron: '0 0 * * 1-5' # Runs daily at 00:00 UTC, Monday to Friday

permissions:
  pull-requests: write

#to cancel currently running workflow for same pr if new changes pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkDependencies:
    name: Check dependencies for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run Dependency-Check
        run: ./gradlew dependencyCheckAnalyze

      - name: Upload Dependency-Check Report
        id: uploadDependencyCheckReport
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: 'build/reports/dependency-check-report.html'

      - name: Upload Dependency-Check report for code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'build/reports/dependency-check-report.sarif'

      - name: Comment artifacts url
        if: success() || failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.number }} --body "Dependency check report: ${{ steps.uploadDependencyCheckReport.outputs.artifact-url }}"