name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  build:
    name: Provide apk
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $KEYSTORE_FILE
          pwd
          ls -l

      - name: Build Release apk
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs