name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Decode Keystore
          env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
            SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

          run: |
            echo $ENCODED_STRING > keystore-b64.txt
            base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

      - name: Build Release apk
          env:
            SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
            SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
            SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: app/build/outputs/apk/release/app-release.apk